{% set name = "pylustrator" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylustrator-{{ version }}.tar.gz
  sha256: 3d800d9f1fab4938a3f64459123918449d2cd42d0b8904e452bf7eff7cd46714

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - natsort
    - numpy
    - matplotlib-base
    - pyqt
    - qtpy
    - qtawesome
    - scikit-image

test:
  imports:
    - pylustrator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rgerum/pylustrator
  summary: Adds interactivity to arrange panels in matplotlib
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
